import streamlit as st
import numpy as np
import easyocr
from PIL import Image
import openai
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta
import time
import base64
import json

# Mobile-optimized page configuration
st.set_page_config(
    page_title="AI Cancer Care Assistant",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="collapsed",  # Better for mobile
)

# Load secrets
OPENAI_API_KEY = st.secrets["OPENAI_API_KEY"]
GMAIL_EMAIL = st.secrets["GMAIL_EMAIL"]
GMAIL_APP_PASSWORD = st.secrets["GMAIL_APP_PASSWORD"]

openai.api_key = OPENAI_API_KEY
reader = easyocr.Reader(['en'])

# Initialize session states
if "conversation" not in st.session_state:
    st.session_state.conversation = []
if "ocr_text" not in st.session_state:
    st.session_state.ocr_text = ""
if "processing_complete" not in st.session_state:
    st.session_state.processing_complete = False
if "user_email" not in st.session_state:
    st.session_state.user_email = ""
if "last_activity" not in st.session_state:
    st.session_state.last_activity = datetime.now()
if "session_start" not in st.session_state:
    st.session_state.session_start = datetime.now()
if "mobile_view" not in st.session_state:
    st.session_state.mobile_view = False

# ========== MOBILE RESPONSIVE LAYOUT ==========
def check_mobile_view():
    """Detect if user is on mobile and adjust layout"""
    # Simple mobile detection based on screen width
    try:
        # This is a basic approach - Streamlit doesn't have direct screen size detection
        # In production, you might want to use JavaScript injection
        st.session_state.mobile_view = st.checkbox("📱 Mobile Optimized View", 
                                                  value=st.session_state.mobile_view,
                                                  help="Enable for better mobile experience")
    except:
        st.session_state.mobile_view = False

def mobile_friendly_columns():
    """Return column layout based on device"""
    if st.session_state.mobile_view:
        return st.columns(1)  # Single column on mobile
    else:
        return st.columns([1, 1])  # Two columns on desktop

# ========== ENHANCED EMAIL FORMATTING ==========
def send_email_via_gmail():
    """Send conversation via Gmail SMTP with CLEAN vertical formatting"""
    if not st.session_state.user_email:
        st.error("❌ Please enter your email address first")
        return False
    
    # Validate email format
    if "@" not in st.session_state.user_email or "." not in st.session_state.user_email:
        st.error("❌ Please enter a valid email address")
        return False
    
    try:
        with st.spinner("📧 Preparing and sending email..."):
            # Gmail SMTP configuration
            smtp_server = "smtp.gmail.com"
            port = 587
            sender_email = GMAIL_EMAIL
            sender_password = GMAIL_APP_PASSWORD
            
            # ENHANCED: Clean vertical email formatting
            email_content = f"""
CANCER CARE ASSISTANT - CONVERSATION SUMMARY
============================================

Generated: {datetime.now().strftime("%Y-%m-%d at %H:%M:%S")}
Session Duration: {str(datetime.now() - st.session_state.session_start).split('.')[0]}
Total Messages: {len(st.session_state.conversation)}

{'='*60}

"""
            
            for i, msg in enumerate(st.session_state.conversation):
                if msg["role"] == "user":
                    email_content += f"""
YOU (Message {i+1}):
{'-'*40}
{msg['content']}

"""
                else:
                    email_content += f"""
AI ASSISTANT (Message {i+1}):
{'-'*40}
{msg['content']}

"""
                email_content += "═" * 60 + "\n\n"
            
            # Enhanced privacy footer
            email_content += f"""
🔒 PRIVACY & CONFIDENTIALITY
{'='*60}
• This conversation summary is for your personal records only
• All data has been automatically cleared from our system
• Please store this email securely
• For medical emergencies, contact your healthcare provider immediately

📞 Need Help?
• Primary Doctor: [Your Doctor's Contact]
• Emergency: 911 or your local emergency number
• Mental Health Support: 988 Suicide & Crisis Lifeline

Generated by AI Cancer Care Assistant
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""
            
            # Create message
            message = MIMEMultipart()
            message["From"] = f"Cancer Care Assistant <{sender_email}>"
            message["To"] = st.session_state.user_email
            message["Subject"] = f"Cancer Care Summary - {datetime.now().strftime('%Y-%m-%d')}"
            message.attach(MIMEText(email_content, "plain"))
            
            # Send email
            context = ssl.create_default_context()
            with smtplib.SMTP(smtp_server, port) as server:
                server.starttls(context=context)
                server.login(sender_email, sender_password)
                server.sendmail(sender_email, st.session_state.user_email, message.as_string())
        
        # SUCCESS NOTIFICATION with clear formatting
        st.success(f"""
        ✅ **EMAIL SENT SUCCESSFULLY!**

        📬 **Delivered To:** {st.session_state.user_email}
        ⏰ **Sent Time:** {datetime.now().strftime("%H:%M:%S")}
        📋 **Content:** {len(st.session_state.conversation)} messages
        📄 **Format:** Clean vertical layout with timestamps

        💡 **Please check:**
        • Your **INBOX** for the summary
        • **SPAM/JUNK** folder if not received
        • Email will have clear **SECTION DIVIDERS**

        🔒 **Privacy:** All data cleared from this session
        """)
        
        # Auto-clear after successful email (optional)
        time.sleep(5)
        st.info("🔄 You may start a new session now")
        return True
        
    except Exception as e:
        st.error(f"""
        ❌ **EMAIL FAILED TO SEND**

        🔧 **Error Details:** {str(e)}
        
        💡 **Troubleshooting Tips:**
        • Verify email address is correct
        • Check internet connection
        • Ensure Gmail App Password is valid
        • Try again in a few minutes
        """)
        return False

# ========== ENHANCED UX COMPONENTS ==========
def show_quick_stats():
    """Show quick statistics in a compact format"""
    if st.session_state.conversation:
        user_msgs = len([msg for msg in st.session_state.conversation if msg["role"] == "user"])
        assistant_msgs = len([msg for msg in st.session_state.conversation if msg["role"] == "assistant"])
        
        # Compact stats display
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Your Messages", user_msgs)
        with col2:
            st.metric("AI Responses", assistant_msgs)
        with col3:
            total_chars = sum(len(msg["content"]) for msg in st.session_state.conversation)
            st.metric("Conversation", f"~{total_chars // 1000}KB")

def enhanced_document_processor(uploaded_files):
    """Enhanced document processing with mobile support"""
    if not uploaded_files:
        return
    
    # Progress tracking
    progress_bar = st.progress(0)
    status_text = st.empty()
    
    st.session_state.ocr_text = ""
    
    for i, uploaded_file in enumerate(uploaded_files):
        status_text.text(f"📄 {i+1}/{len(uploaded_files)}: {uploaded_file.name}")
        
        try:
            img = Image.open(uploaded_file)
            
            # Mobile-optimized image display
            if st.session_state.mobile_view:
                st.image(img, caption=uploaded_file.name, use_column_width=True)
            else:
                with st.expander(f"📄 {uploaded_file.name}", expanded=(i==0)):
                    st.image(img, use_column_width=True)
            
            # OCR processing
            with st.spinner(f"Reading {uploaded_file.name}..."):
                extracted_text = " ".join(reader.readtext(np.array(img), detail=0))
                st.session_state.ocr_text += extracted_text + "\n\n"
                
                if extracted_text.strip():
                    st.success(f"✓ Text from {uploaded_file.name}")
                else:
                    st.warning(f"⚠ No text in {uploaded_file.name}")
        
        except Exception as e:
            st.error(f"❌ {uploaded_file.name}: {e}")
        
        progress_bar.progress((i + 1) / len(uploaded_files))
        time.sleep(0.3)
    
    status_text.text("✅ Documents ready!")
    time.sleep(1)
    status_text.empty()
    progress_bar.empty()

# ========== MOBILE-OPTIMIZED MAIN LAYOUT ==========
def main():
    # Check and apply mobile settings
    check_mobile_view()
    
    # Mobile-optimized header
    st.title("🏥 AI Cancer Care Assistant")
    
    # Quick session info
    session_duration = datetime.now() - st.session_state.session_start
    st.caption(f"🕒 Session: {str(session_duration).split('.')[0]} | 📱 Mobile: {'On' if st.session_state.mobile_view else 'Off'}")
    
    st.markdown("---")
    
    # MOBILE-RESPONSIVE LAYOUT
    if st.session_state.mobile_view:
        # SINGLE COLUMN FOR MOBILE
        mobile_single_column_layout()
    else:
        # TWO COLUMNS FOR DESKTOP
        desktop_two_column_layout()
    
    # Enhanced footer
    show_enhanced_footer()

def mobile_single_column_layout():
    """Single column layout for mobile devices"""
    
    # Document Upload Section
    st.subheader("📁 Upload Documents")
    uploaded_files = st.file_uploader(
        "Choose medical files:",
        type=['pdf','png','jpg','jpeg'],
        accept_multiple_files=True,
        help="Lab reports, diagnosis, medical images"
    )
    
    if uploaded_files:
        enhanced_document_processor(uploaded_files)
        
        if st.button("🎯 Generate Analysis", type="primary", use_container_width=True):
            if st.session_state.ocr_text.strip():
                generate_analysis()
            else:
                st.warning("Please upload readable documents first")
    
    st.markdown("---")
    
    # Chat Section
    st.subheader("💬 Consultation")
    render_chat_interface()
    
    # Quick Stats
    if st.session_state.conversation:
        st.markdown("---")
        show_quick_stats()

def desktop_two_column_layout():
    """Two column layout for desktop"""
    left_col, right_col = st.columns([1, 1])
    
    with left_col:
        st.subheader("📁 Upload Documents")
        uploaded_files = st.file_uploader(
            "Choose medical files:",
            type=['pdf','png','jpg','jpeg'],
            accept_multiple_files=True,
            help="Lab reports, diagnosis, medical images"
        )
        
        if uploaded_files:
            enhanced_document_processor(uploaded_files)
            
            if st.button("🎯 Generate Analysis", type="primary", use_container_width=True):
                if st.session_state.ocr_text.strip():
                    generate_analysis()
                else:
                    st.warning("Please upload readable documents first")
    
    with right_col:
        st.subheader("💬 Consultation")
        render_chat_interface()
        
        if st.session_state.conversation:
            st.markdown("---")
            show_quick_stats()

def render_chat_interface():
    """Render chat interface for both mobile and desktop"""
    chat_container = st.container()
    
    with chat_container:
        for i, msg in enumerate(st.session_state.conversation):
            if msg["role"] == "user":
                with st.chat_message("user", avatar="👤"):
                    st.markdown(msg["content"])
            else:
                with st.chat_message("assistant", avatar="🤖"):
                    st.markdown(msg["content"])
                    
                    # Mobile-optimized suggested questions
                    if msg.get("type") == "initial_analysis" and i == len(st.session_state.conversation) - 1:
                        st.markdown("---")
                        st.markdown("**💡 Quick Questions:**")
                        
                        if st.session_state.mobile_view:
                            # Single column buttons for mobile
                            for idx, question in enumerate(SUGGESTED_QUESTIONS):
                                if st.button(f"❓ {question}", key=f"mq_{idx}", use_container_width=True):
                                    handle_suggested_question(question)
                        else:
                            # Two columns for desktop
                            col1, col2 = st.columns(2)
                            for idx, question in enumerate(SUGGESTED_QUESTIONS):
                                col = col1 if idx % 2 == 0 else col2
                                with col:
                                    if st.button(f"❓ {question}", key=f"q_{idx}", use_container_width=True):
                                        handle_suggested_question(question)
    
    # Chat input
    if st.session_state.processing_complete:
        st.markdown("---")
        user_input = st.chat_input("Type your question here...")
        if user_input:
            handle_user_message(user_input)

def show_enhanced_footer():
    """Enhanced footer with clear actions"""
    st.markdown("---")
    
    if st.session_state.mobile_view:
        # Stacked buttons for mobile
        col1, col2 = st.columns(2)
        with col1:
            if st.button("🔄 New Session", use_container_width=True):
                clear_session_data()
        with col2:
            if st.button("📧 Email Summary", use_container_width=True):
                if st.session_state.conversation:
                    send_email_via_gmail()
                else:
                    st.warning("No conversation to send")
        
        # Email input below buttons
        st.session_state.user_email = st.text_input(
            "Email address for summary:",
            placeholder="your.email@example.com",
            value=st.session_state.user_email,
            key="mobile_email_input"
        )
    else:
        # Horizontal layout for desktop
        col1, col2, col3 = st.columns([1, 2, 1])
        with col1:
            if st.button("🔄 New Session", use_container_width=True):
                clear_session_data()
        with col2:
            email_col1, email_col2 = st.columns([3, 1])
            with email_col1:
                st.session_state.user_email = st.text_input(
                    "Email for summary:",
                    placeholder="your.email@example.com",
                    value=st.session_state.user_email,
                    label_visibility="collapsed"
                )
            with email_col2:
                if st.button("Send", use_container_width=True, type="secondary"):
                    if st.session_state.conversation:
                        send_email_via_gmail()
                    else:
                        st.warning("No conversation to send")
        with col3:
            st.caption(f"Messages: {len(st.session_state.conversation)}")

# ========== CORE FUNCTIONS (Keep your existing ones) ==========
def generate_analysis():
    """Your existing generate_analysis function"""
    with st.spinner("🤖 Analyzing your medical documents..."):
        try:
            prompt = f"""Based on the following medical report content, please provide:
1. Concise health summary
2. 5 suggested questions for your cardiologist/primary doctor (limit to 5 questions maximum)
3. Professional dietitian advice based on health report

Medical report content:
{st.session_state.ocr_text}

Please respond in a professional, caring manner. Keep the questions limited to 5 maximum to avoid overwhelming the patient."""

            response = openai.chat.completions.create(
                model="gpt-5-mini",
                messages=[{"role": "user", "content": prompt}]
            )
            ai_output = response.choices[0].message.content
            
            st.session_state.conversation.append({
                "role": "assistant", 
                "content": ai_output,
                "type": "initial_analysis"
            })
            st.session_state.processing_complete = True
            st.success("✅ Analysis completed! You can now ask follow-up questions.")
            st.rerun()
            
        except Exception as e:
            st.error(f"❌ Analysis failed: {e}")

def handle_user_message(user_input):
    """Your existing handle_user_message function"""
    st.session_state.conversation.append({"role": "user", "content": user_input})
    st.session_state.last_activity = datetime.now()
    
    with st.spinner("🤖 Thinking..."):
        try:
            messages = [{"role": msg["role"], "content": msg["content"]} 
                       for msg in st.session_state.conversation]
            
            response = openai.chat.completions.create(
                model="gpt-5-mini",
                messages=messages
            )
            ai_reply = response.choices[0].message.content
            st.session_state.conversation.append({"role": "assistant", "content": ai_reply})
            st.session_state.last_activity = datetime.now()
            st.rerun()
            
        except Exception as e:
            st.error(f"❌ Failed to generate response: {e}")

def handle_suggested_question(question):
    """Your existing handle_suggested_question function"""
    st.session_state.conversation.append({"role": "user", "content": question})
    st.session_state.last_activity = datetime.now()
    
    with st.spinner("🤖 Thinking..."):
        try:
            messages = [{"role": msg["role"], "content": msg["content"]} 
                       for msg in st.session_state.conversation]
            
            response = openai.chat.completions.create(
                model="gpt-5-mini",
                messages=messages
            )
            ai_reply = response.choices[0].message.content
            st.session_state.conversation.append({"role": "assistant", "content": ai_reply})
            st.session_state.last_activity = datetime.now()
            st.rerun()
            
        except Exception as e:
            st.error(f"❌ Failed to generate response: {e}")

def clear_session_data():
    """Clear all session data"""
    for key in list(st.session_state.keys()):
        del st.session_state[key]
    st.rerun()

# Suggested questions
SUGGESTED_QUESTIONS = [
    "Can you explain my test results in simple terms?",
    "What are the most important lifestyle changes I should make?",
    "What symptoms should I monitor and report to my doctor?",
    "Are there any foods or supplements I should avoid?",
    "When should I schedule my next follow-up appointment?"
]

# Run the app
if __name__ == "__main__":
    main()




































































